<nav class="white" role="navigation">
    <div class="nav-wrapper container">
        <a id="logo-container" href="<?php echo site_url(); ?>" class="brand-logo">Logo</a>
        <ul class="right hide-on-med-and-down">
            <li>
                <a href="<?php echo site_url();?>login"><i class="material-icons right">account_circle</i>Iniciar sesión</a>
            </li>
        </ul>
        <ul id="nav-mobile" class="side-nav">
            <li>
                <a href="<?php echo site_url();?>login"><i class="material-icons left">account_circle</i>Iniciar sesión</a>
            </li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
</nav>