<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Proyecto Final</h5>
                <p class="grey-text text-lighten-4">La presente implementación corresponde a un diseño de los alumnos Federico Joaquín y Martín Buron, en el contexto del desarrollo de su proyecto final de carrera.</p>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Enlaces asociados</h5>
                <ul>
                    <li><a class="white-text" href="http://uns.edu.ar">UNS</a></li>
                    <li><a class="white-text" href="http://cs.uns.edu.ar">DCIC</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Parallax template by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>