<footer class="page-footer teal">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">Contexto</h5>
                <p class="grey-text text-lighten-4">
                   El presente sitio web corresponde a un desarrollo de los alumnos Martín Buron Brarda y Federico Joaquín, en el contexto de su proyecto final de carrera. 
                   El mismo está adapatado al nivel de complejidad requerido, y no contempla su uso de forma masiva ni comercial, estando actualmente en etapa de evaluación.
                </p>
            </div>
            <div class="col l3 s12 right">
                <h5 class="white-text">Enlaces asociados</h5>
                <ul>
                    <li><a class="white-text" href="http://uns.edu.ar">Universidad Nacional del Sur</a></li>
                    <li><a class="white-text" href="http://cs.uns.edu.ar">Dpto. Cs. e Ing. de la Computación</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Parallax template by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>