<!-- MODAL REFERENCIA -->
<div id="modal_referencia" class="modal">
    <hr>
    <h5 class="center">Referencias</h5>
    <hr>
    <div class="modal-content">
        <div class="row">
            <div class="col s12 l2 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/marcas/r.png" alt="Recurso Disponible"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Recurso Disponible</span>
                </div>
            </div>
            <div class="col s12 l2 offset-l1 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/marcas/r_d.png" alt="Recurso ocupado"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Recurso Ocupado</span>
                </div>
            </div>
            <div class="col s12 l2 offset-l1 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/origen.png" alt="Marca origen"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Marca Origen Viaje</span>
                </div>
            </div>
            <div class="col s12 l2 offset-l1 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/destino.png" alt="Marca destino"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Marca Destino Viaje</span>
                </div>
            </div>
            <div class="col s12 l2 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/p.png" alt="Procesando"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Pedido Procesando</span>
                </div>
            </div>
            <div class="col s12 l2 offset-l1 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/a.png" alt="Aceptado"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Pedido Aceptado</span>
                </div>
            </div>
            <div class="col s12 l2 offset-l1 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/r.png" alt="Rechazado"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Pedido Rechazado</span>
                </div>
            </div>
            <div class="col s12 l2 offset-l1 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/ad.png" alt="A Despachar"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Pedido A Despachar</span>
                </div>
            </div>
            <div class="col s12 l2 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/d.png" alt="Despachado"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Pedido Despachado</span>
                </div>
            </div>
            <div class="col s12 l2 offset-l1 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle" src="<?php echo site_url()?>img/referencia/f.png" alt="Finalizado"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Pedido Finalizado</span>
                </div>
            </div>
        </div>
    </div>
</div>