<!-- MODAL NOSOTROS -->
<div id="modal_nosotros" class="modal">
    <hr>
    <h5 class="center">Nosotros</h5>
    <hr>
    <h6 class="center">..: Alumnos de Ing. en Sist. de Computación :..</h6>
    <div class="modal-content">
        <div class="row">
            <div class="col s12 l3 offset-l2 card-panel grey lighten-5 z-depth-1 center-align">
                <div class="row center-align">
                    <img class="circle img-nosotros" src="<?php echo site_url()?>img/nosotros/Martin.png" alt="Martin Buron"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Martín <b>BURON.</b><br><b>LU: 96362.</b></span>
                </div>
            </div>
            <div class="col s12 l3 offset-l2 card-panel grey lighten-5 z-depth-1">
                <div class="row center-align">
                    <img class="circle img-nosotros" src="<?php echo site_url()?>img/nosotros/Federico.png" alt="Federico Joaquín"> 
                </div>
                <div class="row center-align">
                    <span class="black-text">Federico <b>JOAQUÍN.</b><br><b>LU: 96550.</b></span>
                </div>
            </div>
        </div>
    </div>
</div>