<!-- CSS  -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="<?php echo site_url(); ?>css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
<link href="<?php echo site_url(); ?>css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>

<!--  Scripts-->
<script src="<?php echo site_url(); ?>js/jquery-2.2.0.min.js"></script>
<script src="<?php echo site_url(); ?>js/materialize.min.js"></script>
<script src="<?php echo site_url(); ?>js/init.js"></script>